heat_template_version: 2015-10-15

description: >
  HOT to deploy nested-contrail-kubernetes stack

parameters:

  public_network_fqdn:
    type: string
    description: FQDN of the public network

  image_name:
    type: string
    description: Name of the image

  flavor_type:
    type: string
    description: Flavor type of the instance 

  master_instance_name:
    type: string
    description: Name of the master instance

  slave_instance_name:
    type: string
    description: Name of the slave instance

resources:

  template_VirtualMachineInterface_Master:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      name: { get_param: master_instance_name } 
      virtual_network_refs: [{ get_param: public_network_fqdn }]

  template_VirtualMachineInterface_Slave:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      name: { get_param: slave_instance_name } 
      virtual_network_refs: [{ get_param: public_network_fqdn }]

  template_InstanceIp_Master:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ template_VirtualMachineInterface_Master ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: template_VirtualMachineInterface_Master }]
      virtual_network_refs: [{ get_param: public_network_fqdn }]

  template_InstanceIp_Slave:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ template_VirtualMachineInterface_Slave ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: template_VirtualMachineInterface_Slave }]
      virtual_network_refs: [{ get_param: public_network_fqdn }]

  template_Instance_Master:
    type: OS::Nova::Server
    depends_on: [ template_InstanceIp_Master ]
    properties:
      name: { get_param: master_instance_name }
      image: { get_param: image_name }
      flavor: { get_param: flavor_type }
      networks:
        - port: { get_resource: template_VirtualMachineInterface_Master }
      user_data:
        get_resource: template_BootStrap
      user_data_format: RAW

  template_Instance_Slave:
    type: OS::Nova::Server
    depends_on: [ template_InstanceIp_Slave ]
    properties:
      name: { get_param: slave_instance_name }
      image: { get_param: image_name }
      flavor: { get_param: flavor_type }
      networks:
        - port: { get_resource: template_VirtualMachineInterface_Slave }
      user_data:
        get_resource: template_BootStrap
      user_data_format: RAW

  template_BootStrap:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: { get_resource: template_CloudInit }

  template_CloudInit:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/sh
        yum install epel-release vim NetworkManager -y
        systemctl start NetworkManager && sudo systemctl enable NetworkManager
        yum update -y

outputs:

  master_instance_ip:
    description: Public IP of master instance
    value: { get_attr: [ template_Instance_Slave, networks, { str_split: [':', { get_param: public_network_fqdn }, 2] }, 0 ] }

  slave_instance_ip:
    description: Public IP of slave instance
    value: { get_attr: [ template_Instance_Slave, networks, { str_split: [':', { get_param: public_network_fqdn }, 2] }, 0 ] }
